on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main

name: Build/Publish Image Docker
jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v1
      - name: login to dockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 0lucho0/${{ github.repository }}:${{ github.sha }}